package edu.cs401group3.crm.commands;

public enum Commands {
	ADD_USER, EDIT_USER, DELETE_USER,
	ADD_CLIENT, EDIT_CLIENT, DELETE_CLIENT, 
	ADD_RECORD, EDIT_RECORD, DELETE_RECORD, 
	ADD_GROUP, EDIT_GROUP, DELETE_GROUP,
	IMPORT, EXPORT, SAVE, DUMMY_COMMAND
}
